### ISSUE TITLE
varnish.service entered failed state

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#54]
After running the script and rebooting, the varnish service fails to load.

 ● varnish.service - Varnish a high-perfomance HTTP accelerator
   Loaded: loaded (/etc/systemd/system/varnish.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-08-22 13:37:41 CEST; 34ms ago
  Process: 2442 ExecStart=/usr/sbin/varnishd -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -u varnish -g varnish -p thread_pool_min=200 -p thread_pool_max=4000 -p thread_pool_add_delay=2 -p cli_timeout=25 -p cli_buffer=26384 -p feature=+esi_disable_xml_check,+esi_ignore_other_elements -p vcc_allow_inline_c=on -p timeout_linger=100 -S /etc/varnish/secret -P /var/run/varnish.pid -s malloc,2G (code=exited, status=1/FAILURE)
  Process: 901 ExecStartPre=/usr/sbin/varnishd -C -f /etc/varnish/default.vcl (code=exited, status=0/SUCCESS)

Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -s file,<dir_or_file>
Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -s file,<dir_or_file>,<size>
Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -s file,<dir_or_file>,<size>,<granularity>
Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -s persistent (experimental)
Aug 22 13:37:41 dw2.web.com varnishd[2442]: -T address:port              # Telnet listen address and port
Aug 22 13:37:41 dw2.web.com varnishd[2442]: -t TTL                       # Default TTL
Aug 22 13:37:41 dw2.web.com varnishd[2442]: -V                           # version
Aug 22 13:37:41 dw2.web.com varnishd[2442]: -W waiter                    # Waiter implementation
Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -W epoll
Aug 22 13:37:41 dw2.web.com varnishd[2442]: #   -W poll

**Comment by magenx** [comment]
should be fixed now.
varnish service file configured together with varnish.params file
```
/etc/systemd/system/varnish.service
/etc/varnish/varnish.params
```

**Comment by gladroger** [comment]
Sorry, I reran the script on a fresh centos install but it still failed. 

` ● varnish.service - Varnish a high-perfomance HTTP accelerator
   Loaded: loaded (/etc/systemd/system/varnish.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-08-22 15:11:02 CEST; 8ms ago
  Process: 2570 ExecStart=/usr/sbin/varnishd -P /var/run/varnish.pid -u ${VARNISH_USER} -g ${VARNISH_GROUP} -f ${VARNISH_VCL_CONF} -a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} -S ${VARNISH_SECRET_FILE} -s ${VARNISH_STORAGE} ${DAEMON_OPTS} (code=exited, status=1/FAILURE)
  Process: 923 ExecStartPre=/usr/sbin/varnishd -C -f ${VARNISH_VCL_CONF} (code=exited, status=0/SUCCESS)

Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: return(1); Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: int __match_proto__(vcl_func_f) Aug 22 15:11:02 dw2.website.com varnishd[923]: VGC_function_vcl_miss(VRT_CTX) Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: /* ... from ('Builtin' Line 115 Pos 5) */ Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: VRT_count(ctx, 24); Aug 22 15:11:02 dw2.website.com varnishd[923]: VRT_handling(ctx, VCL_RET_FETCH); Aug 22 15:11:02 dw2.website.com varnishd[923]: return (1); Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: } Aug 22 15:11:02 dw2.website.com varnishd[923]: int __match_proto__(vcl_func_f) Aug 22 15:11:02 dw2.website.com varnishd[923]: VGC_function_vcl_pass(VRT_CTX) Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: /* ... from ('Builtin' Line 83 Pos 5) */ Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: { Aug 22 15:11:02 dw2.website.com varnishd[923]: VRT_count(ctx, 14); Aug 22 15:11:02 dw2.website.com varnishd[923]: VRT_handling(ctx, VCL_RET_FETCH); Aug 22 15:11:02 dw2.website.com varnishd[923]: return (1); 
`
Got two other issues unfortunately.

**Comment by magenx** [comment]
sorry, looks like varnish is very picky to variables.
